spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security-app
    username: root
    password: admin
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
security:
    jwt:
      expiration-minutes: 30
      secret-key: Q2xhdmUgU2VjcmV0YSBwYXJhIHByb3llY3RvIEp3dCAxMjM0NTY3ODkgQWJjZA==